expense/urls.py
from django.contrib import admin
from django.urls import path
from .import views

from django.contrib.auth import views as auth_views

app_name = "expense"

urlpatterns = [
    path('add-expense/', views.addExpense, name = "add-expense"),
    path('add-expense-batch/', views.addExpenseBatch, name = "add-expense-batch"),
    path('update-expense/<int:id>', views.updateExpense, name = "update-expense"),
    path('get-delete-expense/<int:id>', views.getDeleteExpense, name = "get-delete-expense"),
    path('delete-expense/<int:id>', views.deleteExpense, name = "delete-expense"),
    path('add-company/', views.addCompany, name = "add-company"),
    path('add-category/', views.addCategory, name = "add-category"),
    path('add-unit/', views.addUnit, name = "add-unit"),
    path('download-expense-excel/', views.downloadExpenseExcel, name = "download-expense-excel"),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "home"

urlpatterns = [
]

romanofabrika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

from home.views import index, dashboard
from material.views import materials
from expense.views import expenses
from order.views import orders
from product.views import products
from finance.views import finances
from loan.views import loans, bchLoans
from report.views import reports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('dashboard/', dashboard, name="dashboard"),
    path('user/', include("user.urls")),
    path('materials/', include("material.urls")),
    path('materials/', materials, name="materials"),
    path('expenses/', include("expense.urls")),
    path('expenses/', expenses, name="expenses"),
    path('orders/', include("order.urls")),
    path('orders/', orders, name="orders"),
    path('products/', include("product.urls")),
    path('products/', products, name="products"),
    path('finances/', include("finance.urls")),
    path('finances/', finances, name="finances"),
    path('loans/', include("loan.urls")),
    path('loans/', loans, name="loans"),
    path('bch-loans/', bchLoans, name="bch-loans"),
    path('reports/', include("report.urls")),
    path('reports/', reports, name="reports"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expense/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django.utils import timezone

import datetime



# Create your models here.

class Company(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Firma")

    class Meta:
        verbose_name_plural = "companies"
        ordering = ['title']

    def __str__(self):
        return self.title
    
class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Kategori")

    class Meta:   
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title
    
class Unit(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Birim")

    def __str__(self):
        return self.title
    
class Expense(models.Model):
    company = models.ForeignKey(Company, on_delete = models.CASCADE, default = 1, verbose_name = "Firma")
    category = models.ForeignKey(Category, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Kategori")
    title = models.CharField(max_length=200, verbose_name = "Ürün/Hizmet")
    unit = models.ForeignKey(Unit, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Birim")
    created_date = models.DateField(auto_now_add = False, default = timezone.now, editable = True, verbose_name = "Tarih")
    quantity = models.FloatField(verbose_name = "Miktar", default = 1)
    price = models.FloatField(verbose_name = "Birim Fiyat", default = 0.00)
    total = models.FloatField(null = True, blank = True)
    
    def save(self, ** kwargs):
        self.total = self.quantity * self.price
        return super(Expense, self).save()
    
    class Meta:
        ordering = ['-created_date']
    
    def __str__(self):
        return self.title
    

class Excel(models.Model):
    file = models.FileField(blank =True, null = True, verbose_name = "Excel Dosyası")
    
@receiver(pre_save, sender = Expense)  
def testDef(sender, instance, **kwargs):
    print(sender.objects.get(id = instance.id).title)
    print(instance.title)

expense/forms.py
from django import forms

from .models import Expense, Company, Excel, Category, Unit

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }
        
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }

class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ["created_date", "company", "category", "title", "unit", "quantity", "price"]
        
        widgets = {
            "created_date" : forms.DateInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "company" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "category" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "unit" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"}),
            "quantity" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "price" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"})
        }
    
    # def __init__(self, *args, **kwargs):
    #     super(ExpenseForm, self).__init__(*args, **kwargs)
    #     self.fields['company'].empty_label = "Firma Seçiniz"
        
class ExcelForm(forms.ModelForm):
    class Meta:
        model = Excel
        fields = ["file"]
        
        widgets = {
            "file" : forms.FileInput(attrs = {"class" : "form-control", "accept" : ".xlsx", "style" : "background-color: #fff;"})
        }

expense/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from django.contrib import messages
from django.http import FileResponse

from django.utils import translation

from django.utils import timezone

from .models import Expense, Company, Category, Unit
from .forms import ExpenseForm, CompanyForm, ExcelForm, CategoryForm, UnitForm

from datetime import date, timedelta
import pandas as pd

# Create your views here.

@login_required(login_url = "user:login")
def expenses(request):
    tag = "Giderler"
    lineGraphTag = "Gider Grafği (30 Gün)"
    pieGraphTag = "Gider Kategori Dağılımı (30 Gün)"
    
    translation.activate('tr')
    
    expenses = Expense.objects.filter().order_by("-created_date")
    categories = Category.objects.filter()
    
    #####Line Graph#####
    days = []

    for i in range(31):
        days.append((timezone.now().date()-timedelta(days=i)).isoformat())

    days.reverse()
    
    dataExpenses = []
    
    for day in days:
        dailyExpense = []
        for expense in expenses:
            if str(expense.created_date) == str(day):
                dailyExpense.append(float(expense.total))
            else:
                dailyExpense.append(0)
        dataExpenses.append(sum(dailyExpense))
    
    lineData = []

    for i in range(31):
        lineData.append({
            "day" : days[i],
            "data" : round(dataExpenses[i],2)
        })
    
    ########################
    
    #####Pie Graph#####
    dataCategory = []
    dataTotal = []
    
    for category in categories:
        categoryExpense = []
        for expense in expenses:
            if str(expense.category) == str(category.title):
                categoryExpense.append(float(expense.total))
        dataCategory.append(category.title)
        dataTotal.append(sum(categoryExpense))
    
    pieData = []
    
    for i in range(len(dataCategory)):
        pieData.append({
            "category" : dataCategory[i],
            "data" : round(dataTotal[i],2)
        })

    ##########################
    
    context = {
                "tag" : tag,
                "lineGraphTag" : lineGraphTag,
                "pieGraphTag" : pieGraphTag,
                "expenses" : expenses,
                "lineData" : lineData,
                "pieData" : pieData
            }

    return render(request, "expense/expenses.html", context)

@login_required(login_url = "user:login")
def addExpense(request):
    tag = "Gider Ekle"
    
    form = ExpenseForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            expense = form.save(commit = False)
            expense.save()
            
            messages.success(request, "Gider Başarıyla Eklendi...")

            return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'expense/expenseForm.html', context)

@login_required(login_url = "user:login")
def downloadExpenseExcel(request):
    response = FileResponse(open('./excelfile/add-expense.xlsx', 'rb'))
    return response


@login_required(login_url = "user:login")
def addExpenseBatch(request):
    tag = "Excel İle Gider Ekle"

    expenses = Expense.objects.filter()

    form = ExcelForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        if form.is_valid():
            newfile = form.save(commit = False)
            newfile.save()

            if request.FILES.getlist("file") == []:
                messages.info(request, "Dosya Bulunamadı!")
                return HttpResponse(status=204)
            try:
                data = pd.read_excel(str(newfile.file.path))
                df = pd.DataFrame(data)
            except ValueError:
                newfile.delete()
                messages.info(request, "Şablon Excel formatında olmalıdır!")
                return HttpResponse(status=204)

            try:
                for i in range(len(df["ÜRÜN BAŞLIĞI"])):
                    if pd.isnull(df["ÜRÜN BAŞLIĞI"][i]):
                        newfile.delete()
                        messages.info(request, "Bazı ürün/ürünlerin başlığı girilmemiş! Lütfen boş olan başlıkları doldurup tekrar deneyin...")
                        return HttpResponse(status=204)
                    
                    #####Select'lerde hücre boşsa default değeri bulup doldurmak#####
                    try:
                        company = get_object_or_404(Company, title = df["FİRMA"][i])
                    except:
                        if pd.isnull(df["FİRMA"][i]):
                            defaultCompanyId = Expense._meta.get_field('company').get_default()
                            defaultCompany = get_object_or_404(Company, id = defaultCompanyId)
                            company = defaultCompany
                        else:
                            company = Company.objects.create(title = df["FİRMA"][i])
                    try:
                        category = get_object_or_404(Category, title = df["KATEGORİ"][i])
                    except:
                        if pd.isnull(df["KATEGORİ"][i]):
                            defaultCategoryId = Expense._meta.get_field('category').get_default()
                            defaultCategory = get_object_or_404(Category, id = defaultCategoryId)
                            category = defaultCategory
                        else:
                            category = Category.objects.create(title = df["KATEGORİ"][i])
                    try:
                        unit = get_object_or_404(Unit, title = df["BİRİM"][i])
                    except:
                        if pd.isnull(df["BİRİM"][i]):
                            defaultUnitId = Expense._meta.get_field('unit').get_default()
                            defaultUnit= get_object_or_404(Unit, id = defaultUnitId)
                            unit = defaultUnit
                        else:
                            unit = Unit.objects.create(title = df["BİRİM"][i])
                    #######################################################################
                    
                    newexpense = Expense.objects.create(
                        created_date = df["TARİH"][i],
                        company = company,
                        category = category,
                        title = df["ÜRÜN BAŞLIĞI"][i],
                        unit = unit,
                        quantity = df["MİKTAR"][i],
                        price = df["BİRİM TUTAR"][i],
                        )
            except KeyError:
                newfile.delete()
                messages.info(request, "Şablon Hatalı! Sütun başlıklarını kontrol ediniz ve tekrar deneyiniz.")
                return HttpResponse(status=204)

            except ValueError as e:
                print(e)
                newfile.delete()
                messages.info(request, "Şablon Hatalı! Sayı girilmesi gereken alanlara karakter girilmediğini veya boş bırakılmadığını kontrol ediniz ve tekrar deneyiniz.")
                return HttpResponse(status=204)

            newfile.delete()

        messages.success(request, "Ürün Başarıyla Eklendi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "expenses" : expenses,
            }

    return render(request, "expense/expenseBatchForm.html", context)

@login_required(login_url = "user:login")
def updateExpense(request, id):
    expenses = Expense.objects.filter()
    expense = get_object_or_404(Expense, id = id)
    
    form = ExpenseForm(request.POST or None, request.FILES or None, instance = expense)
    
    tag = expense.title

    if request.method == "POST":
        if form.is_valid():
            expense = form.save(commit = False)
            expense.save()
            
        messages.success(request, "Değişiklikler Kaydedildi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "expenses" : expenses,
                "expense" : expense
            }

    return render(request, "expense/expenseForm.html", context)

@login_required(login_url = "user:login")
def getDeleteExpense(request, id):
    expense = get_object_or_404(Expense, id = id)

    context = {
                "expense" : expense
            }
    
    return render(request, "expense/deleteExpenseForm.html", context)

@login_required(login_url = "user:login")
def deleteExpense(request, id):
    expense = get_object_or_404(Expense, id = id)
    
    expense.delete()

    messages.success(request, "Gider Silindi...")
    
    return redirect("expenses")

@login_required(login_url = "user:login")
def addCompany(request):
    tag = "Firma Ekle"
    
    form = CompanyForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            company = form.save(commit = False)
            company.save()

        messages.success(request, "Firma Başarıyla Eklendi...")

        return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'expense/companyForm.html', context)

@login_required(login_url = "user:login")
def addCategory(request):
    tag = "Kategori Ekle"
    
    form = CategoryForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            category = form.save(commit = False)
            category.save()

        messages.success(request, "Kategori Başarıyla Eklendi...")

        return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    

templates/expense/categoryForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Kategori Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Kategori İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'expense:add-expense' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/expense/companyForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Firma Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Firma İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'expense:add-expense' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/expense/deleteExpenseForm.html
<div hx-post="{{ request.path }}" class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Silinsin mi?</h5>
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
        <a class="btn btn-danger" type="submit" href="/expenses/delete-expense/{{expense.id}}">Sil</a>
    </div>
</div>

templates/expense/expenseBatchForm.html
<form hx-post="{{ request.path }}" class="modal-content" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">{{tag}}</h5>
    </div>
    <div class="modal-body">
        <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label"></label>
        {{ form.file}}
        </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
        <button class="btn btn-danger" type="submit">Yükle</button>
    </div>
</form>
    

templates/expense/expenseForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">{{tag}}</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Tarih</label>
        {{ form.created_date }}
      </div>
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">
          Firma
          {% if expense == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'expense:add-company' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
          {% endif %}
        </label>
        <select class="form-select companySelect" aria-label="Default select example" name="company">
          {% for company in form.company %}
            {{ company }}
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">
          Kategori
          {% if expense == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'expense:add-category' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
          {% endif %}
        </label>
        <select class="form-select" aria-label="Default select example" name="category">
          {% for category in form.category %}
            {{ category }}
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Ürün/Hizmet</label>
        {{ form.title }}
      </div>
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">
          Birim
          {% if expense == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'expense:add-unit' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
          {% endif %}
        </label>
        <select class="form-select" aria-label="Default select example" name="unit">
          {% for unit in form.unit %}
            {{ unit }}
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Miktar</label>
        {{ form.quantity }}
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Birim Tutar</label>
        {{ form.price }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/expense/expenses.html
{% extends 'layout/dashboardLayout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="globalBoxes">
    <div class="box">
        <button class="btn btn-info" hx-get="{% url 'expense:add-expense' %}" hx-target="#addUpdateDataDialog" style="margin-bottom: 20px;">Gider Ekle</button>
        <a class="btn btn-success" hx-get="{% url 'expense:add-expense-batch' %}" hx-target="#addUpdateDataDialog" style="margin-bottom: 20px;">Excel İle Ekle</a>
        <a class="btn btn-success" href="{% url 'expense:download-expense-excel' %}" style="margin-bottom: 20px;">Excel Şablonunu İndir</a>
        <table id="expenseTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Tarih</th>
                    <th>Firma</th>
                    <th>Kategori</th>
                    <th>Ürün/Hizmet</th>
                    <th>Birim</th>
                    <th>Miktar</th>
                    <th>Birim Tutar</th>
                    <th>Toplam Tutar</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for expense in expenses %}
                    <tr>
                        <td data-order="1479686400">{{expense.created_date}}</td>
                        <td>{{expense.company}}</td>
                        <td>{{expense.category}}</td>
                        <td>{{expense.title}}</td>
                        <td>{{expense.unit}}</td>
                        <td>{{expense.quantity}}</td>
                        <td>₺ {{expense.price}}</td>
                        <td>₺ {{expense.total|floatformat:2}}</td>
                        <td>
                            <button class="btn btn-info" hx-get="{% url 'expense:update-expense' expense.id %}" hx-target="#addUpdateDataDialog">Düzenle</button>
                        </td>
                        <td>
                            <button class="btn btn-danger" hx-get="{% url 'expense:get-delete-expense' expense.id %}" hx-target="#addUpdateDataDialog">Sil</button>
                        </td>
                    </tr>
                {% endfor %}
                
            </tbody>
            <tfoot>
                <tr>
                    <th>Tarih</th>
                    <th>Firma</th>
                    <th>Kategori</th>
                    <th>Ürün/Hizmet</th>
                    <th>Birim</th>
                    <th>Miktar</th>
                    <th>Birim Tutar</th>
                    <th>Toplam Tutar</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="sales-graph">
    {% include "includes/graph/lineGraph.html" %}
    {% include "includes/graph/pieGraph.html" %}
</div>

<script>
    $(document).ready(function () {
        $('#expenseTable').DataTable({
            order: [[0, 'desc']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json'
            }
        });
    });

    /*Line Chart*/
    const ctxLineChart = document.getElementById('line-chart').getContext('2d');

    new Chart(ctxLineChart, {
        type: 'line',
        data: {
        labels: [{% for item in lineData %} "{{ item.day }}", {% endfor %}],
        datasets: [{
            label: '',
            data: [{% for item in lineData %} {{ item.data }}, {% endfor %}],
            fill: true,
            backgroundColor: 'rgba(255, 56, 0, 0.2)',
            borderColor: '#ff3800',
            borderWidth: 1,
            tension: 0.5
        }]
        },
        options: {
            plugins: {
                legend: {
                    display:false
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    grid: {
                        color: "rgba(0, 0, 0, 0.05)"
                    }
                },
                x: {
                    grid: {
                        display:false
                    }
                }
            }
        }
    });

    /*Pie Chart*/
    const ctxPieChart = document.getElementById('pie-chart').getContext('2d');

    new Chart(ctxPieChart, {
        type: 'pie',
        data: {
        labels: [{% for item in pieData %} "{{ item.category }}", {% endfor %}],
        datasets: [{
            label: '',
            data: [{% for item in pieData %} {{ item.data }}, {% endfor %}],
            borderWidth: 1,
            hoverOffset: 4
        }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            aspectRatio: 1,
            plugins: {
                legend: {
                    position: 'bottom'
                }
            },
            scales: {
                xAxes: [{
                    gridLines: {
                        display:false
                    }
                }],
                yAxes: [{
                    gridLines: {
                        display:false
                    }   
                }]
            }
        }
    });

</script>

{% endblock body %}

templates/expense/unitForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Birim Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Birim İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'expense:add-expense' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>