home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "home"

urlpatterns = [
]

material/urls.py
from django.contrib import admin
from django.urls import path
from .import views

from django.contrib.auth import views as auth_views

app_name = "material"

urlpatterns = [
    #path('materials/', views.materials, name = "materials"),
    path('add-material/', views.addMaterial, name = "add-material"),
    path('update-material/<int:id>', views.updateMaterial, name = "update-material"),
    path('get-delete-material/<int:id>', views.getDeleteMaterial, name = "get-delete-material"),
    path('delete-material/<int:id>', views.deleteMaterial, name = "delete-material"),
    path('add-source/', views.addSource, name = "add-source"),
    path('add-category/', views.addCategory, name = "add-category"),
    path('add-unit/', views.addUnit, name = "add-unit"),
]

romanofabrika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

from home.views import index, dashboard
from material.views import materials
from expense.views import expenses
from order.views import orders
from product.views import products
from finance.views import finances
from loan.views import loans, bchLoans
from report.views import reports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('dashboard/', dashboard, name="dashboard"),
    path('user/', include("user.urls")),
    path('materials/', include("material.urls")),
    path('materials/', materials, name="materials"),
    path('expenses/', include("expense.urls")),
    path('expenses/', expenses, name="expenses"),
    path('orders/', include("order.urls")),
    path('orders/', orders, name="orders"),
    path('products/', include("product.urls")),
    path('products/', products, name="products"),
    path('finances/', include("finance.urls")),
    path('finances/', finances, name="finances"),
    path('loans/', include("loan.urls")),
    path('loans/', loans, name="loans"),
    path('bch-loans/', bchLoans, name="bch-loans"),
    path('reports/', include("report.urls")),
    path('reports/', reports, name="reports"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

material/models.py
from django.db import models

# Create your models here.

class Source(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Kaynak")
    slug = models.SlugField(unique=True)

    class Meta:
        unique_together = ('slug',)    
        verbose_name_plural = "sources"

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Kategori")
    
    class Meta:   
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title
    
class Unit(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Birim")

    def __str__(self):
        return self.title

class Material(models.Model):
    source = models.ForeignKey(Source, on_delete = models.CASCADE, default = 2, verbose_name = "Kaynak")
    category = models.ForeignKey(Category, on_delete = models.CASCADE, default = 1, verbose_name = "Kategori")
    title = models.CharField(max_length=200, verbose_name = "Malzeme İsmi")
    unit = models.ForeignKey(Unit, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Birim")
    quantity = models.FloatField(verbose_name = "Miktar", default = 1)
    price = models.FloatField(verbose_name = "Birim Fiyat", default = 0.00)
    
    def __str__(self):
        return self.title

material/forms.py
from django import forms

from .models import Material, Source, Category, Unit

class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }
        
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }
        
class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ["title"]
        
        widgets = {
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ["source", "category", "title", "unit", "quantity", "price"]
        
        widgets = {
            "source" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "category" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"}),
            "unit" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "quantity" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "price" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"})
        }

material/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from django.contrib import messages

from .models import Material
from .forms import MaterialForm, SourceForm, CategoryForm, UnitForm

# Create your views here.

#@user_passes_test(lambda u: u.is_superuser, login_url = "/admin")
@login_required(login_url = "user:login")
def materials(request):
    tag = "Malzemeler"
    
    materials = Material.objects.filter()
    
    context = {
                "tag" : tag,
                "materials" : materials
            }

    return render(request, "material/materials.html", context)

@login_required(login_url = "user:login")
def addMaterial(request):
    tag = "Malzeme Ekle"
    
    form = MaterialForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            material = form.save(commit = False)
            material.save()

        messages.success(request, "Malzeme Başarıyla Eklendi...")

        return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'material/materialForm.html', context)

@login_required(login_url = "user:login")
def updateMaterial(request, id):
    materials = Material.objects.filter()
    material = get_object_or_404(Material, id = id)
    
    form = MaterialForm(request.POST or None, request.FILES or None, instance = material)
    
    tag = material.title

    if request.method == "POST":
        if form.is_valid():
            material = form.save(commit = False)
            material.save()
            
        messages.success(request, "Değişiklikler Kaydedildi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "materials" : materials,
                "material" : material
            }

    return render(request, "material/materiaLForm.html", context)

@login_required(login_url = "user:login")
def getDeleteMaterial(request, id):
    material = get_object_or_404(Material, id = id)

    context = {
                "material" : material
            }
    
    return render(request, "material/deleteMaterialForm.html", context)

@login_required(login_url = "user:login")
def deleteMaterial(request, id):
    material = get_object_or_404(Material, id = id)
    
    material.delete()

    messages.success(request, "Malzeme Silindi...")
    
    return redirect("materials")

@login_required(login_url = "user:login")
def addSource(request):
    tag = "Kaynak Ekle"
    
    form = SourceForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            source = form.save(commit = False)
            source.save()

        messages.success(request, "Kaynak Başarıyla Eklendi...")

        return HttpResponse(status=204)

    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'material/sourceForm.html', context)

@login_required(login_url = "user:login")
def addCategory(request):
    tag = "Kategori Ekle"
    
    form = CategoryForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            category = form.save(commit = False)
            category.save()

        messages.success(request, "Kategori Başarıyla Eklendi...")

        return HttpResponse(status=204)

    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'material/categoryForm.html', context)

@login_required(login_url = "user:login")
def addUnit(request):
    tag = "Birim Ekle"
    
    form = UnitForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":

        if form.is_valid():
            unit = form.save(commit = False)
            unit.save()

        messages.success(request, "Birim Başarıyla Eklendi...")

        return HttpResponse(status=204)

    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'material/unitForm.html', context)

templates/material/categoryForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Kategori Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Kategori İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'material:add-material' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/material/deleteMaterialForm.html
<div hx-post="{{ request.path }}" class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Silinsin mi?</h5>
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
        <a class="btn btn-danger" type="submit" href="/materials/delete-material/{{material.id}}">Sil</a>
    </div>
</div>

templates/material/materialForm.html
<form hx-post="{{ request.path }}" class="modal-content">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">{{tag}}</h5>
  </div>
  <div class="modal-body">
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">
        Kaynak
        {% if material == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'material:add-source' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
        {% endif %}
      </label>
      <select class="form-select companySelect" aria-label="Default select example" name="source">
        {% for source in form.source %}
          {{ source }}
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">
        Kategori
        {% if material == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'material:add-category' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
        {% endif %}
      </label>
      <select class="form-select" aria-label="Default select example" name="category">
        {% for category in form.category %}
          {{ category }}
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">Ürün/Hizmet</label>
      {{ form.title }}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">
        Birim
        {% if material == None %}<!--Buradaki if bloğunun amacı, firma ekle butonunu sadece gider ekleme modal'ında göstermek-->
            <a class="addAttributeButton" hx-get="{% url 'material:add-unit' %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-plus"></i></a>
        {% endif %}
      </label>
      <select class="form-select" aria-label="Default select example" name="unit">
        {% for unit in form.unit %}
          {{ unit }}
        {% endfor %}
      </select>
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">Miktar</label>
      {{ form.quantity }}
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">Birim Tutar</label>
      {{ form.price }}
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
    <button class="btn btn-danger" type="submit">Kaydet</button>
  </div>
</form>

templates/material/materials.html
{% extends 'layout/dashboardLayout.html' %}

{% block body %}
<tbody ></tbody>
<div class="globalBoxes">
<div class="box">
    <button class="btn btn-info" hx-get="{% url 'material:add-material' %}" hx-target="#addUpdateDataDialog" style="margin-bottom: 20px;">Malzeme Ekle</button>
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Kategori</th>
                <th>Malzeme İsmi</th>
                <th>Birim</th>
                <th>Miktar</th>
                <th>Birim Fiyat</th>
                <th>Düzenle</th>
                <th>Sil</th>
            </tr>
        </thead>
        <tbody>
            {% for material in materials %}
                <tr>
                    <td>{{material.category}}</td>
                    <td>{{material.title}}</td>
                    <td>{{material.unit}}</td>
                    <td>{{material.quantity}}</td>
                    <td>₺ {{material.price}}</td>
                    <td>
                        <button class="btn btn-info" hx-get="{% url 'material:update-material' material.id %}" hx-target="#addUpdateDataDialog">Düzenle</button>
                    </td>
                    <td>
                        <button class="btn btn-danger" hx-get="{% url 'material:get-delete-material' material.id %}" hx-target="#addUpdateDataDialog">Sil</button>
                    </td>
                </tr>
            {% endfor %}
            
        </tbody>
        <tfoot>
            <tr>
                <th>Malzeme Tipi</th>
                <th>Malzeme İsmi</th>
                <th>Birim</th>
                <th>Miktar</th>
                <th>Birim Fiyat</th>
                <th>düzenle</th>
                <th>Sil</th>
            </tr>
        </tfoot>
    </table>
</div>
</div>

<div class="globalBoxes">
    <div class="line-graph box">
        <div class="head">
            <div class="title">Grafik</div>
            <i class='bx bx-cog'></i>
        </div>
        <canvas id="line-chart"></canvas>
        <div class="button goDetailButton">
            <a href="">Detaylı Raporlar</a>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#example').DataTable({
            order: [[0, 'desc']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json'
            }
        });
    });

    /*Line Chart*/
    const lineChart = document.getElementById('line-chart').getContext('2d');
    const myLineChart = new Chart(lineChart, {
    type: 'line',
    data: {
        labels: [{% for item in lineData %} "{{ item.day }}", {% endfor %}],
        datasets: [{
            label: '',
            data: [{% for item in lineData %} {{ item.sale }}, {% endfor %}],
            backgroundColor: [
                'rgba(255, 56, 0, 0.2)',
            ],
            borderColor: [
                '#ff3800',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            },
            xAxes: [{
            gridLines: {
                color: "rgba(0, 0, 0, 0)",
            }
        }],
        yAxes: [{
            gridLines: {
                color: "rgba(0, 0, 0, 0.05)",
            }   
        }]
        },
        legend: {
            display: false
        }
    }
});
</script>

{% endblock body %}

templates/material/sourceForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Kaynak Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Kaynak İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'material:add-material' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/material/unitForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Birim Ekle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Birim İsmi</label>
        {{ form.title }}
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" hx-get="{% url 'material:add-material' %}" hx-target="#addUpdateDataDialog">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>