home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "home"

urlpatterns = [
]

loan/urls.py
from django.contrib import admin
from django.urls import path
from .import views

from django.contrib.auth import views as auth_views

app_name = "loan"

urlpatterns = [
    path('add-loan/', views.addLoan, name = "add-loan"),
    path('update-loan/<int:id>', views.updateLoan, name = "update-loan"),
    path('update-installment-status/<int:id>', views.updateInstallmentStatus, name = "update-installment-status"),
    path('get-delete-loan/<int:id>', views.getDeleteLoan, name = "get-delete-loan"),
    path('delete-loan/<int:id>', views.deleteLoan, name = "delete-loan"),
]

romanofabrika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

from home.views import index, dashboard
from material.views import materials
from expense.views import expenses
from order.views import orders
from product.views import products
from finance.views import finances
from loan.views import loans, bchLoans
from report.views import reports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('dashboard/', dashboard, name="dashboard"),
    path('user/', include("user.urls")),
    path('materials/', include("material.urls")),
    path('materials/', materials, name="materials"),
    path('expenses/', include("expense.urls")),
    path('expenses/', expenses, name="expenses"),
    path('orders/', include("order.urls")),
    path('orders/', orders, name="orders"),
    path('products/', include("product.urls")),
    path('products/', products, name="products"),
    path('finances/', include("finance.urls")),
    path('finances/', finances, name="finances"),
    path('loans/', include("loan.urls")),
    path('loans/', loans, name="loans"),
    path('bch-loans/', bchLoans, name="bch-loans"),
    path('reports/', include("report.urls")),
    path('reports/', reports, name="reports"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loan/models.py
from django.db import models

from django.utils import timezone

# Create your models here.

class Bank(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Banka")

    class Meta:
        verbose_name_plural = "banks"
        ordering = ['title']

    def __str__(self):
        return self.title

class InstallmentStatus(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Taksit Durumu")

    class Meta:   
        verbose_name_plural = "installment statuses"

    def __str__(self):
        return self.title
    
class LoanStatus(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Kredi Durumu")

    class Meta:   
        verbose_name_plural = "loan statuses"

    def __str__(self):
        return self.title
    
class LoanOption(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Hesaplama")

    class Meta:   
        verbose_name_plural = "loan options"

    def __str__(self):
        return self.title


class Loan(models.Model):
    status = models.ForeignKey(LoanStatus, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Kredi Durumu")
    bank = models.ForeignKey(Bank, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Banka")
    title = models.CharField(max_length=200, verbose_name = "Kredi İsmi")
    option = models.ForeignKey(LoanOption, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Hesaplama/Giriş")
    amount = models.FloatField(verbose_name = "Kredi Tutarı", default = 0.00)
    cost = models.FloatField(verbose_name = "Masraf", default = 0.00)
    transmitted_amount = models.FloatField(null = True, blank = True, verbose_name = "Hesaba Aktarılan Tutar")
    interest = models.FloatField(verbose_name = "Faiz", default = 0.00)
    total_debt = models.FloatField(null = True, blank = True, verbose_name = "Toplam Borç")
    installment_count = models.IntegerField(verbose_name = "Taksit Sayısı", default = 1)
    installment_deferral = models.IntegerField(verbose_name = "Taksit Erteleme", default = 0)
    installments = models.JSONField(null = True, blank = True,verbose_name = "Taksitler")
    start_date = models.DateField(auto_now_add = False, default = timezone.now, editable = True, verbose_name = "Kredi Başlangıç Tarihi")
    next_installment = models.DateField(null = True, blank = True,verbose_name = "Taksitler")
    installment_status = models.ForeignKey(InstallmentStatus, on_delete = models.SET_DEFAULT, default = 3, verbose_name = "Taksit Durumu")
    completed_installment = models.IntegerField(verbose_name = "Tamamlanan Taksitler", default = 0)
    
    def save(self, ** kwargs):
        if self.option.id == 1:
            self.transmitted_amount = self.transmitted_amount
            self.total_debt = self.total_debt
        else:
            self.transmitted_amount = self.amount - self.cost
            self.total_debt = round(((self.amount * ((((self.interest / 100) * 1.15 * 1.05) * ((1 + ((self.interest / 100) * 1.15 * 1.05)) ** self.installment_count) ) / (((1 + ((self.interest / 100) * 1.15 * 1.05)) ** self.installment_count) - 1))) * self.installment_count) + (self.amount / 100), 2)
        return super(Loan, self).save()
    
    class Meta:
        ordering = ['-start_date']
    
    def __str__(self):
        return self.title
    
    
class BCHLoan(models.Model):
    status = models.ForeignKey(LoanStatus, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Kredi Durumu")
    bank = models.ForeignKey(Bank, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Banka")
    title = models.CharField(max_length=200, verbose_name = "Kredi İsmi")
    option = models.ForeignKey(LoanOption, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Hesaplama/Giriş")
    amount = models.FloatField(verbose_name = "Anapara", default = 0.00)
    remaining_amount = models.FloatField(verbose_name = "Kalan Anapara", default = 0.00)
    cost = models.FloatField(verbose_name = "Masraf", default = 0.00)
    transmitted_amount = models.FloatField(null = True, blank = True, verbose_name = "Hesaba Aktarılan Tutar")
    interest = models.FloatField(verbose_name = "Faiz", default = 0.00)
    interest_amount = models.FloatField(verbose_name = "Faiz Tutarı", default = 0.00)
    total_debt = models.FloatField(null = True, blank = True, verbose_name = "Toplam Borç")
    start_date = models.DateField(auto_now_add = False, default = timezone.now, editable = True, verbose_name = "Kredi Başlangıç Tarihi")
    end_date = models.DateField(auto_now_add = False, default = timezone.now, editable = True, verbose_name = "Kredi Bitiş Tarihi")
    interest_payment = models.JSONField(null = True, blank = True,verbose_name = "Faiz Ödemeleri")
    amount_payment = models.JSONField(null = True, blank = True,verbose_name = "Anapara Ödemeleri")
    interest_updates = models.JSONField(null = True, blank = True,verbose_name = "Faiz Güncellemeleri")
    
    def save(self, ** kwargs):
        if self.option.id == 1:
            self.transmitted_amount = self.transmitted_amount
            self.total_debt = self.total_debt
        else:
            self.transmitted_amount = self.amount - self.cost
            self.total_debt = self.remaining_amount + self.interest_amount
        return super(BCHLoan, self).save()
    
    class Meta:
        ordering = ['-start_date']
    
    def __str__(self):
        return self.title

loan/forms.py
from django import forms

from .models import Loan, InstallmentStatus, BCHLoan

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ["status", "bank", "title", "option", "amount", "cost", "transmitted_amount", "interest", "total_debt", "installment_count", "installment_deferral", "start_date"]
        
        widgets = {
            "status" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "bank" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"}),
            "option" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "amount" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "cost" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "transmitted_amount" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "interest" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "total_debt" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "installment_count" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "installment_deferral" : forms.NumberInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "start_date" : forms.DateInput(attrs = {"class" : "form-control", "style" : "background-color: #fff;"})
        }
    
    # def __init__(self, *args, **kwargs):
    #     super(ExpenseForm, self).__init__(*args, **kwargs)
    #     self.fields['company'].empty_label = "Firma Seçiniz"
    
class InstallmentStatusForm(forms.ModelForm):
    class Meta:
        model = Loan #burada Loan modelini seçmemeizin sebebi order'da olduğu gibi.
        fields = ["installment_status"]
        
        widgets = {
             "installment_status" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"})
        }
        
class BCHLoanForm(forms.ModelForm):
    class Meta:
        model = BCHLoan
        fields = ["status", "bank", "title", "option", "amount", "remaining_amount", "cost", "transmitted_amount", "interest", "interest_amount", "total_debt", "start_date", "end_date"]
        
        widgets = {
            "status" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "bank" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"}),
            "title" : forms.Textarea(attrs = {"class" : "form-control", "rows" : "1", "style" : "background-color: #fff;"})
        }

loan/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from django.contrib import messages

from django.utils import translation

from .forms import LoanForm, InstallmentStatusForm, BCHLoanForm

from datetime import datetime
import calendar
import json
from dateutil.relativedelta import relativedelta
import ast

from .models import Loan, InstallmentStatus, BCHLoan

# Create your views here.

@login_required(login_url = "user:login")
def loans(request):
    tag = "Krediler"
    
    translation.activate('tr')
    
    loans = Loan.objects.filter()
    
    for loan in loans:
        installmentStatuses = []
        for installment in loan.installments:
            installmentStatuses.append(installment["installmentStatus"])
        loan.completed_installment = installmentStatuses.count("Ödendi")
            
        for installment in loan.installments:
            if datetime.strptime(installment["installmentDate"], "%Y-%m-%d").date() > datetime.now().date():
                #print("Gelecek Taksit: " + str(installment["installmentDate"]))
                if installment["installmentStatus"] == "Ödenmedi":
                    loan.next_installment = datetime.strptime(installment["installmentDate"], "%Y-%m-%d").date()
                    loan.save()
                    break
        
        
        loan.save()
    
    nowDate = datetime.now().date()

        
    
    context = {
                "tag" : tag,
                "loans" : loans,
                "nowDate" : nowDate
            }

    return render(request, "loan/loans.html", context)

@login_required(login_url = "user:login")
def addLoan(request):
    tag = "Kredi Ekle"
    
    form = LoanForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":
        if form.is_valid():
            loan = form.save(commit = False)
            loan.save()
            
            installments = []
            start_date = loan.start_date
            print(start_date + relativedelta(months=1))
            start_date = start_date + relativedelta(months=loan.installment_deferral)
            for count in range(loan.installment_count):
                installments.append({"installmentDate" : str(start_date),
                                     "installmentNo" : count + 1,
                                     "installmentAmount" : round(loan.total_debt / (loan.installment_count - loan.installment_deferral),2),
                                     "installmentStatus" : ""})
                start_date = start_date + relativedelta(months=1)
                
            loan.installments = installments
            loan.save()
            
            
            
            messages.success(request, "Kredi Başarıyla Eklendi...")

            return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'loan/loanForm.html', context)

@login_required(login_url = "user:login")
def updateLoan(request, id):
    installmentStatus = get_object_or_404(InstallmentStatus, id = 3)
    loan = get_object_or_404(Loan, id = id)
    
    form = LoanForm(request.POST or None, request.FILES or None, instance = loan)
    
    tag = loan.title

    if request.method == "POST":
        if form.is_valid():
            loan = form.save(commit = False)
            
            installments = []
            start_date = loan.start_date
            print(start_date + relativedelta(months=1))
            start_date = start_date + relativedelta(months=loan.installment_deferral)
            for count in range(loan.installment_count):
                installments.append({"installmentDate" : str(start_date),
                                     "installmentNo" : count + 1,
                                     "installmentAmount" : round(loan.total_debt / (loan.installment_count - loan.installment_deferral),2),
                                     "installmentStatus" : installmentStatus.title})
                start_date = start_date + relativedelta(months=1)
                
            loan.installments = installments
            
            loan.save()
            
        messages.success(request, "Değişiklikler Kaydedildi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "loan" : loan
            }

    return render(request, "loan/loanForm.html", context)

@login_required(login_url = "user:login")
def updateInstallmentStatus(request, id):
    loan = get_object_or_404(Loan, id = id)
    
    installmentStatuses = InstallmentStatus.objects.filter()
    
    form = InstallmentStatusForm(request.POST or None, request.FILES or None, instance = loan)
    
    tag = loan.title

    if request.method == "POST":
        print(form.data)
        if form.is_valid():
            print(form.data)
            formDataList = form.data.getlist("installment_status")
            for i in range(loan.installment_count):
                theStatus = get_object_or_404(InstallmentStatus, id = int(formDataList[i]))
                loan.installments[i]["installmentStatus"] = theStatus.title
            loan.save()
            
        messages.success(request, "Değişiklikler Kaydedildi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "loan" : loan,
                "installmentStatuses" : installmentStatuses
            }

    return render(request, "loan/installmentStatusForm.html", context)

@login_required(login_url = "user:login")
def getDeleteLoan(request, id):
    loan = get_object_or_404(Loan, id = id)

    context = {
                "loan" : loan
            }
    
    return render(request, "loan/deleteLoanForm.html", context)

@login_required(login_url = "user:login")
def deleteLoan(request, id):
    loan = get_object_or_404(Loan, id = id)
    
    loan.delete()

    messages.success(request, "Kredi Silindi...")
    
    return redirect("loans")


######BCH######
@login_required(login_url = "user:login")
def bchLoans(request):
    tag = "BCH Kredileri"
    
    translation.activate('tr')
    
    loans = BCHLoan.objects.filter()
    
    

        
    
    context = {
                "tag" : tag,
                "loans" : loans
            }

    return render(request, "loan/bchLoans.html", context)

@login_required(login_url = "user:login")
def addBCHLoan(request):
    tag = "Kredi Ekle"
    
    form = BCHLoanForm(request.POST or None, request.FILES or None)
    
    if request.method == "POST":
        if form.is_valid():
            
            
            
            messages.success(request, "Kredi Başarıyla Eklendi...")

            return HttpResponse(status=204)

    
    context = {
                "tag" : tag,
                "form" : form
    }
    
    return render(request, 'loan/loanForm.html', context)

templates/loan/bchLoanForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">{{tag}}</h5>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="mb-3 col">
          <label for="exampleFormControlInput1" class="form-label">
              Kredi Durumu
          </label>
          <select class="form-select companySelect" aria-label="Default select example" name="status">
              {% for status in form.status %}
                  {{ status }}
              {% endfor %}
          </select>
        </div>
        <div class="mb-3 col">
          <label for="exampleFormControlInput1" class="form-label">
              Banka
          </label>
          <select class="form-select companySelect" aria-label="Default select example" name="bank">
              {% for bank in form.bank %}
                  {{ bank }}
              {% endfor %}
          </select>
        </div>
        <div class="mb-3 col-6">
          <label for="exampleFormControlTextarea1" class="form-label">Kredi İsmi</label>
          {{ form.title }}
        </div>
      </div>
      <div class="row">
        <div class="mb-3 col">
          <label for="exampleFormControlInput1" class="form-label">
              Hesaplama Seçeneği
          </label>
          <select class="form-select companySelect" aria-label="Default select example" name="option">
              {% for option in form.option %}
                  {{ option }}
              {% endfor %}
          </select>
        </div>
        <div class="mb-3 col">
          <label for="exampleFormControlTextarea1" class="form-label">Kredi Tutarı</label>
          {{ form.amount }}
        </div>
        <div class="mb-3 col">
          <label for="exampleFormControlTextarea1" class="form-label">Masraf</label>
          {{ form.cost }}
        </div>
      </div>
      <div class="row">
        <div class="mb-3 col">
          <label for="exampleFormControlTextarea1" class="form-label">Hesaba Geçen Tutar</label>
          {{ form.transmitted_amount }}
        </div>
        <div class="mb-3 col">
          <label for="exampleFormControlTextarea1" class="form-label">Faiz</label>
          {{ form.interest }}
        </div>
        <div class="mb-3 col">
            <label for="exampleFormControlTextarea1" class="form-label">Faiz</label>
            {{ form.interest_amount }}
          </div>
        <div class="mb-3 col">
          <label for="exampleFormControlTextarea1" class="form-label">Toplam Geri Ödeme</label>
          {{ form.total_debt }}
        </div>
      </div>
      
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Taksit Sayısı</label>
        {{ form.installment_count }}
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Taksit Erteleme</label>
        {{ form.installment_deferral }}
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Kredi Başlangıç Tarihi</label>
        {{ form.start_date }}
      </div>
      {% if loan.id %}
      <button class="btn btn-light" hx-get="{% url 'loan:update-installment-status' loan.id %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-screwdriver-wrench"></i>&nbsp;Taksitler</button>
      {% endif %}
    </div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>

templates/loan/bchLoans.html
{% extends 'layout/dashboardLayout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="globalBoxes">
    <div class="box">
        <button class="btn btn-info" hx-get="{% url 'loan:add-loan' %}" hx-target="#showImageDialog" style="margin-bottom: 20px;">Kredi Ekle</button>
        <table id="expenseTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Banka</th>
                    <th>Kredi İsmi</th>
                    <th>Kredi Tutarı</th>
                    <th>Başlangıç Tarihi</th>
                    <th>Taksitler</th>
                    <th>Taksit Tutarı</th>
                    <th>Gelecek Taksit Tarihi</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loans %}
                    <tr>
                        <td>{{loan.bank}}</td>
                        <td>{{loan.title}}</td>
                        <td>₺ {{loan.amount}}</td>
                        <td>{{loan.start_date}}</td>
                        <td>{{loan.completed_installment}}/{{loan.installment_count}}</td>
                        <td>₺ {{loan.installments.0.installmentAmount}}</td>
                        <td data-order="1479686400">{{loan.next_installment}}</td>
                        <td>
                            <button class="btn btn-info" hx-get="{% url 'loan:update-loan' loan.id %}" hx-target="#addUpdateDataDialog">Düzenle</button>
                        </td>
                        <td>
                            <button class="btn btn-danger" hx-get="{% url 'loan:get-delete-loan' loan.id %}" hx-target="#addUpdateDataDialog">Sil</button>
                        </td>
                    </tr>
                {% endfor %}
                
            </tbody>
            <tfoot>
                <tr>
                    <th>Banka</th>
                    <th>Kredi İsmi</th>
                    <th>Kredi Tutarı</th>
                    <th>Başlangıç Tarihi</th>
                    <th>Taksitler</th>
                    <th>Taksit Tutarı</th>
                    <th>Gelecek Taksit Tarihi</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="sales-graph">
    {% include "includes/graph/lineGraph.html" %}
    {% include "includes/graph/pieGraph.html" %}
</div>

<script>
    $(document).ready(function () {
        $('#expenseTable').DataTable({
            order: [[0, 'asc']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json'
            }
        });
    });

    /*Line Chart*/
    const lineChart = document.getElementById('line-chart').getContext('2d');
    const myLineChart = new Chart(lineChart, {
        type: 'line',
        data: {
            labels: [{% for item in lineData %} "{{ item.day }}", {% endfor %}],
            datasets: [{
                label: 'Günlük Gider',
                data: [{% for item in lineData %} {{ item.data }}, {% endfor %}],
                backgroundColor: [
                    'rgba(255, 56, 0, 0.2)',
                ],
                borderColor: [
                    '#ff3800',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                },
                xAxes: [{
                gridLines: {
                    color: "rgba(0, 0, 0, 0)",
                }
                }],
                yAxes: [{
                    gridLines: {
                        color: "rgba(0, 0, 0, 0.05)",
                    }   
                }]
            },
            legend: {
                display: false
            }
        }
    });

    /*Pie Chart*/
    const pieChart = document.getElementById('pie-chart').getContext('2d');
    var dataLabels = [{% for item in pieData %} "{{ item.category }}", {% endfor %}];
    const myPieChart = new Chart(pieChart, {
        type: 'doughnut',
        data: {
            labels: dataLabels,
            datasets: [{
                label: '',
                data: [{% for item in pieData %} {{ item.data }}, {% endfor %}],
                backgroundColor: palette(['tol', 'qualitative', 'sequential'], dataLabels.length).map(function(hex) {
                    return '#' + hex;
                  }),
                hoverOffset: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            aspectRatio: 1.2,
            legend: {
                position: 'bottom',
            }
        }  
    });

</script>

{% endblock body %}

templates/loan/deleteLoanForm.html
<div hx-post="{{ request.path }}" class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Silinsin mi?</h5>
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
        <a class="btn btn-danger" type="submit" href="/loans/delete-loan/{{loan.id}}">Sil</a>
    </div>
</div>

templates/loan/loans.html
{% extends 'layout/dashboardLayout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="globalBoxes">
    <div class="box">
        <button class="btn btn-info" hx-get="{% url 'loan:add-loan' %}" hx-target="#showImageDialog" style="margin-bottom: 20px;">Kredi Ekle</button>
        <table id="expenseTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Banka</th>
                    <th>Kredi İsmi</th>
                    <th>Kredi Tutarı</th>
                    <th>Başlangıç Tarihi</th>
                    <th>Taksitler</th>
                    <th>Taksit Tutarı</th>
                    <th>Gelecek Taksit Tarihi</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loans %}
                    <tr>
                        <td>{{loan.bank}}</td>
                        <td>{{loan.title}}</td>
                        <td>₺ {{loan.amount}}</td>
                        <td>{{loan.start_date}}</td>
                        <td>{{loan.completed_installment}}/{{loan.installment_count}}</td>
                        <td>₺ {{loan.installments.0.installmentAmount}}</td>
                        <td data-order="1479686400">{{loan.next_installment}}</td>
                        <td>
                            <button class="btn btn-info" hx-get="{% url 'loan:update-loan' loan.id %}" hx-target="#addUpdateDataDialog">Düzenle</button>
                        </td>
                        <td>
                            <button class="btn btn-danger" hx-get="{% url 'loan:get-delete-loan' loan.id %}" hx-target="#addUpdateDataDialog">Sil</button>
                        </td>
                    </tr>
                {% endfor %}
                
            </tbody>
            <tfoot>
                <tr>
                    <th>Banka</th>
                    <th>Kredi İsmi</th>
                    <th>Kredi Tutarı</th>
                    <th>Başlangıç Tarihi</th>
                    <th>Taksitler</th>
                    <th>Taksit Tutarı</th>
                    <th>Gelecek Taksit Tarihi</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="sales-graph">
    {% include "includes/graph/lineGraph.html" %}
    {% include "includes/graph/pieGraph.html" %}
</div>

<script>
    $(document).ready(function () {
        $('#expenseTable').DataTable({
            order: [[0, 'asc']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json'
            }
        });
    });

    /*Line Chart*/
    const lineChart = document.getElementById('line-chart').getContext('2d');
    const myLineChart = new Chart(lineChart, {
        type: 'line',
        data: {
            labels: [{% for item in lineData %} "{{ item.day }}", {% endfor %}],
            datasets: [{
                label: 'Günlük Gider',
                data: [{% for item in lineData %} {{ item.data }}, {% endfor %}],
                backgroundColor: [
                    'rgba(255, 56, 0, 0.2)',
                ],
                borderColor: [
                    '#ff3800',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                },
                xAxes: [{
                gridLines: {
                    color: "rgba(0, 0, 0, 0)",
                }
                }],
                yAxes: [{
                    gridLines: {
                        color: "rgba(0, 0, 0, 0.05)",
                    }   
                }]
            },
            legend: {
                display: false
            }
        }
    });

    /*Pie Chart*/
    const pieChart = document.getElementById('pie-chart').getContext('2d');
    var dataLabels = [{% for item in pieData %} "{{ item.category }}", {% endfor %}];
    const myPieChart = new Chart(pieChart, {
        type: 'doughnut',
        data: {
            labels: dataLabels,
            datasets: [{
                label: '',
                data: [{% for item in pieData %} {{ item.data }}, {% endfor %}],
                backgroundColor: palette(['tol', 'qualitative', 'sequential'], dataLabels.length).map(function(hex) {
                    return '#' + hex;
                  }),
                hoverOffset: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            aspectRatio: 1.2,
            legend: {
                position: 'bottom',
            }
        }  
    });

</script>

{% endblock body %}