home/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "home"

urlpatterns = [
]

order/urls.py
from django.contrib import admin
from django.urls import path
from .import views

from django.contrib.auth import views as auth_views

app_name = "order"

urlpatterns = [
    #path('orders/', views.orders, name = "orders"),
    path('update-orders/', views.updateOrders, name = "update-orders"),
    path('update-status/<int:id>/<int:counter>', views.updateStatus, name = "update-status"),
    path('show-image/<int:id>/<int:counter>', views.showImage, name = "show-image"),
    path('print-orders/', views.printOrders, name = "print-orders"),
]

romanofabrika/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

from home.views import index, dashboard
from material.views import materials
from expense.views import expenses
from order.views import orders
from product.views import products
from finance.views import finances
from loan.views import loans, bchLoans
from report.views import reports

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('dashboard/', dashboard, name="dashboard"),
    path('user/', include("user.urls")),
    path('materials/', include("material.urls")),
    path('materials/', materials, name="materials"),
    path('expenses/', include("expense.urls")),
    path('expenses/', expenses, name="expenses"),
    path('orders/', include("order.urls")),
    path('orders/', orders, name="orders"),
    path('products/', include("product.urls")),
    path('products/', products, name="products"),
    path('finances/', include("finance.urls")),
    path('finances/', finances, name="finances"),
    path('loans/', include("loan.urls")),
    path('loans/', loans, name="loans"),
    path('bch-loans/', bchLoans, name="bch-loans"),
    path('reports/', include("report.urls")),
    path('reports/', reports, name="reports"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django.utils import timezone

from datetime import datetime
import numpy as np

# Create your models here.

class Status(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Sipariş Durumu")

    class Meta:   
        verbose_name_plural = "statuses"

    def __str__(self):
        return self.title

class Order(models.Model):
    order_id = models.IntegerField(verbose_name = "Sipariş ID", default = 1)
    order_date = models.DateField(auto_now_add = False, default = timezone.now, editable = True, verbose_name = "Sipariş Tarihi")
    delivery_date = models.DateField(null = True, blank = True, editable = True, verbose_name = "Teslimat Tarihi")
    customer_name = models.CharField(max_length=200, verbose_name = "Müşteri Adı")
    products = models.JSONField(verbose_name = "Ürünler")
    cargo_address = models.JSONField(verbose_name = "Teslimat")
    order_status = models.ForeignKey(Status, on_delete = models.SET_DEFAULT, default = 1, verbose_name = "Sipariş Durumu")
    total = models.FloatField(verbose_name = "Sipariş Tutarı", default = 0.00)
    
    def save(self, ** kwargs):
        d_date = np.busday_offset(str(self.order_date), 30, roll='forward')
        self.delivery_date = datetime.strptime(str(d_date), "%Y-%m-%d").date()
        return super(Order, self).save()

    def __str__(self):
        return self.customer_name

order/forms.py
from django import forms

from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["order_status"]
        
        widgets = {
            "order_status" : forms.Select(attrs = {"class" : "form-control", "style" : "background-color: #fff;"})
        }

order/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from django.contrib import messages

from django.utils import translation

from .models import Order, Status
from .forms import OrderForm

import json
from suds.client import Client
from suds.sudsobject import asdict
from datetime import date, timedelta, datetime
import numpy as np

from .tasks import updateOrdersTask


# Create your views here.

#@user_passes_test(lambda u: u.is_superuser, login_url = "/admin")
@login_required(login_url = "user:login")
def orders(request):
    tag = "Siparişler"
    
    translation.activate('tr')
    
    start = datetime(2022, 3, 15).date()
    end = datetime(2022, 4, 16).date()

    days = np.busday_count(start, end)
    dayss = np.busday_offset(str(datetime.now().date()), 30, roll='forward')
    print(datetime.strptime(str(dayss), "%Y-%m-%d").date())
    
    orders = Order.objects.filter()
    
    context = {
                "tag" : tag,
                "orders" : orders
            }

    return render(request, "order/orders.html", context)

@login_required(login_url = "user:login")
def updateOrders(request):
    tag = "Siparişler"
    
    updateOrdersTask.delay()
    
    messages.success(request, "Siparişler Arkaplanda Güncellenecek")
    
    return redirect("orders")

@login_required(login_url = "user:login")
def updateStatus(request, id, counter):
    orders = Order.objects.filter()
    order = get_object_or_404(Order, id = id)
    
    statuses = Status.objects.filter()
    
    form = OrderForm(request.POST or None, request.FILES or None, instance = order)
    
    tag = order.order_id

    if request.method == "POST":
        if form.is_valid():
            order.products[counter]["productStatus"] = form.cleaned_data["order_status"].title
            order.save()
            
        messages.success(request, "Değişiklikler Kaydedildi...")

        return HttpResponse(status=204)

    context = { 
                "tag" : tag,
                "form" : form,
                "orders" : orders,
                "order" : order,
                "counter" : counter,
                "statuses" : statuses
            }

    return render(request, "order/statusForm.html", context)

@login_required(login_url = "user:login")
def showImage(request, id, counter):
    
    order = get_object_or_404(Order, id = id)
    
    src = order.products[counter]["productImg"]
    
    context = {
                "src" : src
            }

    return render(request, "order/imageModal.html", context)

@login_required(login_url = "user:login")
def printOrders(request):
    tag = "Üretim Tablosu"
    
    translation.activate('tr')
    
    orders = Order.objects.filter()
    
    context = {
                "tag" : tag,
                "orders" : orders
            }

    return render(request, "order/printOrders.html", context)

templates/order/orders.html
{% extends 'layout/dashboardLayout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="globalBoxes">
    <div class="box">
        <button class="btn btn-info" onclick="window.print()" style="margin-bottom: 20px;">Sipariş Ekle</button>
        <a class="btn btn-warning" href="{% url 'order:update-orders' %}" style="margin-bottom: 20px;">Güncelle</a>
        <a class="btn btn-danger" href="{% url 'order:print-orders' %}" style="margin-bottom: 20px;">Üretim Tablosu</a>
        <table id="orderTable" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Sipariş ID</th>
                    <th>Sipariş Tarihi</th>
                    <th>Teslimat</th>
                    <th>Adı Soyadı</th>
                    <th>Şehir</th>
                    <th>Ürün</th>
                    <th>Sipariş Tutarı</th>
                    <th>Detay</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr style="vertical-align: middle;">
                        <td>{{order.order_id}}</td>
                        <td data-order="1479686400">{{order.order_date}}</td>
                        <td>{{order.delivery_date}}</td>
                        <td >
                            <ul style="list-style-type: none; margin: 0; padding: 0;">
                                <li>{{order.customer_name}}</li>
                                <li>{{order.cargo_address.AliciTelefon}}</li>
                            </ul>
                        </td>
                        <td >{{order.cargo_address.Ilce}}/{{order.cargo_address.Il}}</td>
                        <td>
                            <ul style="list-style-type: none; margin: 0; padding: 0;">
                                {% for product in order.products %} 
                                    <li style="display: flex; align-items: center; padding: 5px 0;">
                                        <a hx-get="{% url 'order:show-image' order.id forloop.counter0%}" hx-target="#showImageDialog"><img src = "{{product.productImg}}" style="max-width: 100px; cursor: pointer;"></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <span>{{product.productName}}</span>
                                        <span style="margin-left: auto; font-weight: 600;">{{product.productQuantity|floatformat:"0"}}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                                            {% if product.productStatus == "Bekliyor" %}
                                                <button class="btn btn-warning" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-clock"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Üretim Bekliyor" %}
                                                <button class="btn btn-warning" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-clock"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Üretimde" %}
                                                <button class="btn btn-secondary" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-industry"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Üretimi Tamamlandı" %}
                                                <button class="btn btn-info" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-check"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Boyada" %}
                                                <button class="btn btn-primary" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-paint-roller"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Montajda" %}
                                                <button class="btn btn-light" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-screwdriver-wrench"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Paketlemede" %}
                                                <button class="btn btn-light" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-box-open"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Paketlendi" %}
                                                <button class="btn btn-light" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-box"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Nakliyeye Gönderildi" %}
                                                <button class="btn btn-danger" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-truck"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Nakliye Teslim Aldı" %}
                                                <button class="btn btn-danger" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-truck"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Taşıma Durumunda" %}
                                                <button class="btn btn-danger" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-truck"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "Müşteriye Teslim Edildi" %}
                                                <button class="btn btn-success" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-check"></i>&nbsp;{{product.productStatus}}</button>
                                            {% elif product.productStatus == "İptal Edildi" %}
                                                <button class="btn btn-danger" hx-get="{% url 'order:update-status' order.id forloop.counter0 %}" hx-target="#addUpdateDataDialog"><i class="fa-solid fa-ban"></i>&nbsp;{{product.productStatus}}</button>
                                            {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>₺ {{order.total}}</td>
                        <td>
                            <button class="btn btn-info">Detay</button>
                        </td>
                    </tr>
                {% endfor %}
                
            </tbody>
            <tfoot>
                <tr>
                    <th>Sipariş ID</th>
                    <th>Sipariş Tarihi</th>
                    <th>Teslimat</th>
                    <th>Adı Soyadı</th>
                    <th>Şehir</th>
                    <th>Ürün</th>
                    <th>Sipariş Tutarı</th>
                    <th>Detay</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="sales-graph">
    {% include "includes/graph/lineGraph.html" %}
    {% include "includes/graph/pieGraph.html" %}
</div>

<script>
    $(document).ready(function () {
        $('#orderTable').DataTable({
            order: [[0, 'desc']],
            language: {
                url: '//cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json'
            }
        });
    });



    /*Line Chart*/
    const lineChart = document.getElementById('line-chart').getContext('2d');
    const myLineChart = new Chart(lineChart, {
        type: 'line',
        data: {
            labels: [{% for item in lineData %} "{{ item.day }}", {% endfor %}],
            datasets: [{
                label: 'Günlük Gider',
                data: [{% for item in lineData %} {{ item.data }}, {% endfor %}],
                backgroundColor: [
                    'rgba(255, 56, 0, 0.2)',
                ],
                borderColor: [
                    '#ff3800',
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                },
                xAxes: [{
                gridLines: {
                    color: "rgba(0, 0, 0, 0)",
                }
                }],
                yAxes: [{
                    gridLines: {
                        color: "rgba(0, 0, 0, 0.05)",
                    }   
                }]
            },
            legend: {
                display: false
            }
        }
    });

    /*Pie Chart*/
    const pieChart = document.getElementById('pie-chart').getContext('2d');
    var dataLabels = [{% for item in pieData %} "{{ item.category }}", {% endfor %}];
    const myPieChart = new Chart(pieChart, {
        type: 'doughnut',
        data: {
            labels: dataLabels,
            datasets: [{
                label: '',
                data: [{% for item in pieData %} {{ item.data }}, {% endfor %}],
                backgroundColor: palette(['tol', 'qualitative', 'sequential'], dataLabels.length).map(function(hex) {
                    return '#' + hex;
                  }),
                hoverOffset: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            aspectRatio: 1.2,
            legend: {
                position: 'bottom',
            }
        }  
    });

</script>

{% endblock body %}

templates/order/statusForm.html
<form hx-post="{{ request.path }}" class="modal-content">
    {% csrf_token %}
    <div class="modal-header">
      <h5 class="modal-title">Durum Güncelle</h5>
    </div>
    <div class="modal-body">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Durum</label>
        <select class="form-select" aria-label="Default select example" name="order_status">
            {% for status in form.order_status %}
              {{ status }}
            {% endfor %}
        </select>
      </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
      <button class="btn btn-danger" type="submit">Kaydet</button>
    </div>
</form>